apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: centos-boot-infra
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: centos-boot-infra
    app.kubernetes.io/part-of: centos-boot
  name: centos-boot-infra
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: centos-boot-infra
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: centos-boot-infra
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/centos-boot-tenant/centos-boot/centos-boot-infra@sha256:c331ea574f34666a9056411aea542a3c4fa5640b743aea4a5ade0fde96a08b5f
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
