apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: centos-boot-infra
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: centos-boot-infra
    app.kubernetes.io/part-of: centos-boot
  name: centos-boot-infra
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: centos-boot-infra
status:
  loadBalancer: {}
