apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: centos-boot-infra
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/centos-boot-tenant/centos-boot/centos-boot-infra@sha256:17961a5e06fe31c85a49b0b6e650cbdb6c544feff582b61cfe5d2c0a4c8794f6
        name: container-image
        resources: {}
status: {}
