apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: centos-boot-infra
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: centos-boot-infra
    app.kubernetes.io/part-of: centos-boot
  name: centos-boot-infra2fgl
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: centos-boot-infra
    weight: 100
status: {}
