apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: fedora-tier-1-eln
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/centos-boot-tenant/centos-boot/fedora-tier-1-eln@sha256:e574aaaab34db783284415ff9157ccb5eb891a3c4925659454a9dff216a24e5b
        name: container-image
        resources: {}
status: {}
