apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: fedora-tier-1-eln
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/centos-boot-tenant/centos-boot/fedora-tier-1-eln@sha256:22e9e2d63e09d65ecf9a06c5bd90d604055945c0a4f52e8448ddf2666fef9a46
        name: container-image
        resources: {}
status: {}
