apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: fedora-tier-1-eln
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: fedora-tier-1-eln
    app.kubernetes.io/part-of: centos-boot
  name: fedora-tier-1-eln
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: fedora-tier-1-eln
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: fedora-tier-1-eln
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/centos-boot-tenant/centos-boot/fedora-tier-1-eln@sha256:8d37c6ccd1bc25c3cc1c9d31e8d10b85017eff91a3fb3e7ca57277747d05914b
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
