apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: fedora-tier-1-eln
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: fedora-tier-1-eln
    app.kubernetes.io/part-of: centos-boot
  name: fedora-tier-1-eln
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: fedora-tier-1-eln
status:
  loadBalancer: {}
